package FECorba;

/**
* FECorba/FrontEndHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/TLIN/eclipse-workspace/a2.zip_expanded/a2/CORBAa2Lin/FrontEndCorba.idl
* Monday, August 5, 2019 1:22:00 o'clock AM EDT
*/

public final class FrontEndHolder implements org.omg.CORBA.portable.Streamable
{
  public FECorba.FrontEnd value = null;

  public FrontEndHolder ()
  {
  }

  public FrontEndHolder (FECorba.FrontEnd initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FECorba.FrontEndHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FECorba.FrontEndHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FECorba.FrontEndHelper.type ();
  }

}
